## **Import libraries** for data analysis, JSON handling, progress tracking, and file download.
### `pandas` is used for tabular data.
### `json` is used because the API will return structured JSON output.
### `tqdm` helps show progress when processing multiple rows.
### `gdown` downloads the dataset from Google Drive.

In [2]:
import pandas as pd
import json
import tqdm
import gdown

### Download the survey dataset from Google Drive and load it into a DataFrame.

In [3]:
file_id = "1J424k-xkNvq349TyrD9m2s_iDywrHeds"

gdown.download(
    f"https://drive.google.com/uc?id={file_id}",
    "workshop_survey_syn_dataset.csv",
    quiet=False
)

data = pd.read_csv(r'workshop_survey_syn_dataset.csv')

Downloading...
From: https://drive.google.com/uc?id=1J424k-xkNvq349TyrD9m2s_iDywrHeds
To: /content/workshop_survey_syn_dataset.csv
100%|██████████| 440k/440k [00:00<00:00, 6.58MB/s]

### Data quality check

Before using AI, we inspect the dataset so we know what data is being analyzed. This keeps the workflow transparent and helps avoid treating AI output as a black box.

### Check the `size` of the dataset: number of rows and columns.

In [4]:
data.shape

(1000, 9)

### Check the `data type` of each column.

In [5]:
data.dtypes

participant_id             int64
role                      object
department                object
comfort_with_ai           object
main_interest_category    object
main_interest_detail      object
concern_category          object
concern_detail            object
free_text_feedback        object
dtype: object

### Display all column names available in the dataset.

In [6]:
data.columns

Index(['participant_id', 'role', 'department', 'comfort_with_ai',
       'main_interest_category', 'main_interest_detail', 'concern_category',
       'concern_detail', 'free_text_feedback'],
      dtype='object')

### Preview the first 10 rows.

This is to understand the structure of the participant responses before sending anything to the AI.

In [7]:
data.head(10)

,participant_id,role,department,comfort_with_ai,main_interest_category,main_interest_detail,concern_category,concern_detail,free_text_feedback
0,837645,Faculty,Public Health,Comfortable,Grant Writing,Improving clarity and turnaround on competitiv...,Hallucinations and Accuracy,Hard to verify AI output accuracy for technica...,"I already use AI fairly regularly, I'd especia..."
1,475133,Undergraduate Student,Education,Neutral,Student Learning Support,Helping Education students use AI tutors witho...,Academic Misconduct,Students using AI to complete Education assign...,"I have mixed feelings about AI, I really want ..."
2,601099,Faculty,Biology,Uncomfortable,Teaching and Course Design,Designing AI-aware assignments and rubrics for...,Copyright and Intellectual Property,Unclear copyright and ownership rules for AI o...,"I've only dabbled with AI and feel uncertain, ..."
3,269917,Research Scientist,Computer Science,Comfortable,Data Analysis,"Cleaning, exploring, and visualizing Computer ...",Data Privacy,Unclear where AI vendors store and reuse our C...,"I already use AI fairly regularly, I'm keen to..."
4,698457,Administrative Staff,Medicine,Neutral,Research Productivity,Cutting time spent on repetitive analysis step...,Data Privacy,Protecting confidential participant and studen...,"I have mixed feelings about AI, I'd love pract..."
5,556706,Undergraduate Student,Medicine,Comfortable,Programming Assistance,Getting help writing and debugging code for my...,No Major Concerns,Generally optimistic about AI's role in suppor...,I'm reasonably comfortable using AI day to day...
6,467320,Administrative Staff,Information Technology,Uncomfortable,Research Compliance,Ensuring data handling and AI use meet Informa...,No Major Concerns,Generally optimistic about AI's role in suppor...,"I've only dabbled with AI and feel uncertain, ..."
7,255499,Undergraduate Student,Public Health,Comfortable,Career Development,Building AI skills that strengthen my Public H...,Student Overreliance on AI,Worried Public Health students stop thinking c...,I'm reasonably comfortable using AI day to day...
8,660112,Research Scientist,Research Computing,Comfortable,Research Productivity,Cutting time spent on repetitive analysis step...,Student Overreliance on AI,Overreliance eroding foundational competencies...,I'm reasonably comfortable using AI day to day...
9,158089,Graduate Student,Biology,Very Comfortable,Programming Assistance,Getting help writing and debugging code for my...,Research Integrity,Worried AI-generated text could undermine inte...,"I'm an enthusiastic adopter of AI tools, I'm h..."

### Using AI Externally

In this section, we use an AI model through an API instead of manually uploading the dataset into ChatGPT or Claude.

The goal is to make the AI step more systematic, repeatable, and easier to apply across many rows.

In [8]:
from google.colab import userdata

API_KEY = userdata.get('MY_API_KEY')

# Add your API key here.
# In a real workflow, avoid hardcoding API keys directly in notebooks.
# Use environment variables or secure notebook secrets when possible.

In [9]:
# Import the OpenAI client.
from openai import OpenAI

In [10]:
# Create the API client using the provided API key.
# This client is what the notebook uses to send prompts to the AI model.

client = OpenAI(api_key=API_KEY)

### RQ1: Who participated, and how AI-comfortable are different groups?

In [11]:
role_counts = data["role"].value_counts()
department_counts = data["department"].value_counts()
comfort_counts = data["comfort_with_ai"].value_counts()

role_by_comfort_counts = pd.crosstab(
    data["role"],
    data["comfort_with_ai"]
)

role_by_comfort_percent = pd.crosstab(
    data["role"],
    data["comfort_with_ai"],
    normalize="index"
).round(2)

role_counts, department_counts, comfort_counts, role_by_comfort_counts, role_by_comfort_percent

(role
 Undergraduate Student      251
 Graduate Student           197
 Faculty                    153
 Research Staff              78
 Administrative Staff        75
 Research Scientist          56
 Postdoctoral Researcher     51
 Academic Advisor            42
 IT Staff                    36
 Department Chair            23
 Academic Leadership         21
 Librarian                   17
 Name: count, dtype: int64,
 department
 Public Health             129
 Medicine                  119
 Computer Science          112
 Engineering               105
 Biology                    94
 Business                   92
 Humanities                 88
 Education                  83
 Research Computing         43
 Student Affairs            41
 Sponsored Programs         38
 Information Technology     33
 Library Services           23
 Name: count, dtype: int64,
 comfort_with_ai
 Comfortable           338
 Neutral               283
 Very Comfortable      204
 Uncomfortable         134
 Very Uncomfortable     41
 Name: count, dtype: int64,
 comfort_with_ai          Comfortable  Neutral  Uncomfortable  \
 role
 Academic Advisor                  19        8              7
 Academic Leadership                6        8              5
 Administrative Staff              28       16             11
 Department Chair                   6       10              1
 Faculty                           45       40             32
 Graduate Student                  76       55             21
 IT Staff                          13       10              3
 Librarian                          5        5              2
 Postdoctoral Researcher           13       17              7
 Research Scientist                21       15              5
 Research Staff                    25       25             11
 Undergraduate Student             81       74             29

 comfort_with_ai          Very Comfortable  Very Uncomfortable
 role
 Academic Advisor                        8                   0
 Academic Leadership                     2                   0
 Administrative Staff                   14                   6
 Department Chair                        6                   0
 Faculty                                24                  12
 Graduate Student                       39                   6
 IT Staff                                9                   1
 Librarian                               4                   1
 Postdoctoral Researcher                11                   3
 Research Scientist                     12                   3
 Research Staff                         14                   3
 Undergraduate Student                  61                   6  ,
 comfort_with_ai          Comfortable  Neutral  Uncomfortable  \
 role
 Academic Advisor                0.45     0.19           0.17
 Academic Leadership             0.29     0.38           0.24
 Administrative Staff            0.37     0.21           0.15
 Department Chair                0.26     0.43           0.04
 Faculty                         0.29     0.26           0.21
 Graduate Student                0.39     0.28           0.11
 IT Staff                        0.36     0.28           0.08
 Librarian                       0.29     0.29           0.12
 Postdoctoral Researcher         0.25     0.33           0.14
 Research Scientist              0.38     0.27           0.09
 Research Staff                  0.32     0.32           0.14
 Undergraduate Student           0.32     0.29           0.12

 comfort_with_ai          Very Comfortable  Very Uncomfortable
 role
 Academic Advisor                     0.19                0.00
 Academic Leadership                  0.10                0.00
 Administrative Staff                 0.19                0.08
 Department Chair                     0.26                0.00
 Faculty                              0.16                0.08
 Graduate Student                     0.20                0.03
 IT Staff                             0.25                0.03
 Librarian                            0.24                0.06
 Postdoctoral Researcher              0.22                0.06
 Research Scientist                   0.21                0.05
 Research Staff                       0.18                0.04
 Undergraduate Student                0.24                0.02  )

In [ ]:
# The AI is not calculating the counts; pandas already did it.
# Here AI is helping translate the tables into an user-friendly interpretation.

RQ1_prompt = f"""
You are helping explain workshop survey results to a non-technical audience.

Research Question 1:
Who participated in the survey, and how AI-comfortable are different groups?

Use the summary tables below to write a clear answer.

Role counts:
{role_counts.to_string()}

Department counts:
{department_counts.to_string()}

Overall AI comfort counts:
{comfort_counts.to_string()}

Role by AI comfort counts:
{role_by_comfort_counts.to_string()}

Role by AI comfort percentages:
{role_by_comfort_percent.to_string()}

Write:
1. A concise answer to the research question
2. Two or three important patterns
3. One sentence explaining why this matters for planning future AI support
"""

RQ1_response = client.responses.create(
    model="gpt-4.1-mini",
    input=RQ1_prompt
)

print(RQ1_response.output_text)

1. **Answer to the research question:**
The survey included a diverse group of 1,059 participants across roles such as undergraduate and graduate students, faculty, research staff, and administrative personnel, with representation from many departments including Public Health, Medicine, Computer Science, and more. Overall, about half of respondents felt comfortable or very comfortable with AI, though comfort levels varied by role, with graduate students and research scientists showing higher AI comfort compared to faculty and administrative staff.

2. **Important patterns:**
- Graduate students and research scientists reported higher levels of AI comfort (around 39-38% comfortable and 20-21% very comfortable) compared to faculty, who had comparatively lower comfort levels (29% comfortable and 16% very comfortable) and a higher proportion feeling uncomfortable.
- Administrative roles and faculty had the highest percentages of respondents who felt uncomfortable or very uncomfortable with AI, suggesting some hesitation or uncertainty in these groups.
- Undergraduate students showed a balanced distribution, with a significant portion feeling comfortable or very comfortable with AI but also a notable share who were neutral or uncomfortable.

3. **Why this matters:**
Understanding these differences in AI comfort across roles helps tailor future AI training and support programs to meet the specific needs and confidence levels of each group, ensuring more effective adoption and use of AI tools.

### RQ2: What do participants want to use AI for, and what concerns are attached to those interests?

In [12]:
# RQ2: What do participants want to use AI for, and what concerns are attached to those interests?

interest_counts = data["main_interest_category"].value_counts()
concern_counts = data["concern_category"].value_counts()

role_by_interest = pd.crosstab(
    data["role"],
    data["main_interest_category"]
)

interest_by_concern_counts = pd.crosstab(
    data["main_interest_category"],
    data["concern_category"]
)

interest_by_concern_percent = pd.crosstab(
    data["main_interest_category"],
    data["concern_category"],
    normalize="index"
).round(2)

interest_counts, concern_counts, role_by_interest, interest_by_concern_counts, interest_by_concern_percent

(main_interest_category
 Student Learning Support      105
 Programming Assistance        100
 Generative AI Tools            99
 Academic Writing               97
 Grant Writing                  79
 Literature Review              76
 Research Productivity          73
 Career Development             71
 Data Analysis                  68
 Administrative Efficiency      57
 Responsible AI                 43
 Research Compliance            36
 Teaching and Course Design     35
 AI Policy and Governance       33
 Research Computing             28
 Name: count, dtype: int64,
 concern_category
 Data Privacy                           130
 Academic Misconduct                    118
 Hallucinations and Accuracy            116
 Research Integrity                     115
 Lack of Training                       103
 Student Overreliance on AI             103
 No Major Concerns                       90
 Copyright and Intellectual Property     68
 Security Risks                          42
 Cost and Resources                      41
 Bias and Fairness                       39
 Research Compliance                     35
 Name: count, dtype: int64,
 main_interest_category   AI Policy and Governance  Academic Writing  \
 role
 Academic Advisor                                0                 0
 Academic Leadership                             6                 1
 Administrative Staff                            8                 1
 Department Chair                                5                 1
 Faculty                                         1                19
 Graduate Student                                1                30
 IT Staff                                        3                 0
 Librarian                                       3                 2
 Postdoctoral Researcher                         3                 4
 Research Scientist                              1                 2
 Research Staff                                  0                 0
 Undergraduate Student                           2                37

 main_interest_category   Administrative Efficiency  Career Development  \
 role
 Academic Advisor                                 9                  11
 Academic Leadership                              3                   0
 Administrative Staff                            20                   2
 Department Chair                                 2                   0
 Faculty                                          2                   3
 Graduate Student                                 3                  16
 IT Staff                                         2                   1
 Librarian                                        0                   1
 Postdoctoral Researcher                          0                   4
 Research Scientist                               0                   1
 Research Staff                                  13                   2
 Undergraduate Student                            3                  30

 main_interest_category   Data Analysis  Generative AI Tools  Grant Writing  \
 role
 Academic Advisor                     1                    4              1
 Academic Leadership                  0                    3              0
 Administrative Staff                 0                   14              1
 Department Chair                     0                    0              2
 Faculty                              0                    3             39
 Graduate Student                    32                   20              3
 IT Staff                             0                    6              0
 Librarian                            0                    3              0
 Postdoctoral Researcher              5                    2             11
 Research Scientist                  13                    0              3
 Research Staff                      15                    3             18
 Undergraduate Student                2                   41              1

 main_interest_category   Literature Review  Programming Assistance  \
 role
 Academic Advisor                         0                       1
 Academic Leadership                      0                       0
 Administrative Staff                     1                       2
 Department Chair                         1                       1
 Faculty                                 13                       1
 Graduate Student                        36                      27
 IT Staff                                 0                       7
 Librarian                                5                       0
 Postdoctoral Researcher                 13                       0
 Research Scientist                       5                      11
 Research Staff                           0                       1
 Undergraduate Student                    2                      49

 main_interest_category   Research Compliance  Research Computing  \
 role
 Academic Advisor                           0                   1
 Academic Leadership                        3                   0
 Administrative Staff                      16                   1
 Department Chair                           0                   0
 Faculty                                    1                   2
 Graduate Student                           1                   1
 IT Staff                                   1                   8
 Librarian                                  0                   0
 Postdoctoral Researcher                    0                   0
 Research Scientist                         1                   6
 Research Staff                            10                   6
 Undergraduate Student                      3                   3

 main_interest_category   Research Productivity  Responsible AI  \
 role
 Academic Advisor                             0               3
 Academic Leadership                          0               4
 Administrative Staff                         1               3
 Department Chair                             4               2
 Faculty                                     18               9
 Graduate Student                            21               1
 IT Staff                                     0               6
 Librarian                                    0               0
 Postdoctoral Researcher                      8               0
 Research Scientist                          11               1
 Research Staff                               8               1
 Undergraduate Student                        2              13

 main_interest_category   Student Learning Support  Teaching and Course Design
 role
 Academic Advisor                               11                           0
 Academic Leadership                             0                           1
 Administrative Staff                            5                           0
 Department Chair                                0                           5
 Faculty                                        17                          25
 Graduate Student                                4                           1
 IT Staff                                        1                           1
 Librarian                                       3                           0
 Postdoctoral Researcher                         1                           0
 Research Scientist                              1                           0
 Research Staff                                  1                           0
 Undergraduate Student                          61                           2  ,
 concern_category            Academic Misconduct  Bias and Fairness  \
 main_interest_category
 AI Policy and Governance                      2                  3
 Academic Writing                             16                  2
 Administrative Efficiency                     6                  1
 Career Development                            7                  1
 Data Analysis                                 3                  3
 Generative AI Tools                          11                  3
 Grant Writing                                12                  2
 Literature Review                            12                  2
 Programming Assistance                       12                  1
 Research Compliance                           2                  3
 Research Computing                            0                  3
 Research Productivity                         7                  5
 Responsible AI                                4                  3
 Student Learning Support                     18                  6
 Teaching and Course Design                    6                  1

 concern_category            Copyright and Intellectual Property  \
 main_interest_category
 AI Policy and Governance                                      2
 Academic Writing                                              7
 Administrative Efficiency                                     6
 Career Development                                            6
 Data Analysis                                                 6
 Generative AI Tools                                           5
 Grant Writing                                                 9
 Literature Review                                             8
 Programming Assistance                                        4
 Research Compliance                                           0
 Research Computing                                            3
 Research Productivity                                         6
 Responsible AI                                                2
 Student Learning Support                                      3
 Teaching and Course Design                                    1

 concern_category            Cost and Resources  Data Privacy  \
 main_interest_category
 AI Policy and Governance                     5             5
 Academic Writing                             0             8
 Administrative Efficiency                    1            10
 Career Development                           1             8
 Data Analysis                                3            14
 Generative AI Tools                          6            16
 Grant Writing                                6             4
 Literature Review                            2             7
 Programming Assistance                       4            12
 Research Compliance                          4             7
 Research Computing                           1             6
 Research Productivity                        3             9
 Responsible AI                               4             7
 Student Learning Support                     1            15
 Teaching and Course Design                   0             2

 concern_category            Hallucinations and Accuracy  Lack of Training  \
 main_interest_category
 AI Policy and Governance                              3                 4
 Academic Writing                                     14                10
 Administrative Efficiency                             3                 7
 Career Development                                   13                 9
 Data Analysis                                        13                 5
 Generative AI Tools                                   7                13
 Grant Writing                                         6                 7
 Literature Review                                    14                 3
 Programming Assistance                               19                 7
 Research Compliance                                   0                 4
 Research Computing                                    1                 1
 Research Productivity                                 5                 7
 Responsible AI                                        4                 6
 Student Learning Support                             12                12
 Teaching and Course Design                            2                 8

 concern_category            No Major Concerns  Research Compliance  \
 main_interest_category
 AI Policy and Governance                    4                    1
 Academic Writing                           14                    3
 Administrative Efficiency                   2                    4
 Career Development                          5                    1
 Data Analysis                               5                    4
 Generative AI Tools                        12                    0
 Grant Writing                               2                    4
 Literature Review                           6                    1
 Programming Assistance                     18                    2
 Research Compliance                         4                    4
 Research Computing                          2                    3
 Research Productivity                       1                    7
 Responsible AI                              4                    0
 Student Learning Support                   10                    1
 Teaching and Course Design                  1                    0

 concern_category            Research Integrity  Security Risks  \
 main_interest_category
 AI Policy and Governance                     0               2
 Academic Writing                            12               0
 Administrative Efficiency                    5               8
 Career Development                           9               1
 Data Analysis                                6               2
 Generative AI Tools                          8               5
 Grant Writing                               16               4
 Literature Review                           15               2
 Programming Assistance                      10               4
 Research Compliance                          4               3
 Research Computing                           3               4
 Research Productivity                       13               2
 Responsible AI                               3               2
 Student Learning Support                     9               2
 Teaching and Course Design                   2               1

 concern_category            Student Overreliance on AI
 main_interest_category
 AI Policy and Governance                             2
 Academic Writing                                    11
 Administrative Efficiency                            4
 Career Development                                  10
 Data Analysis                                        4
 Generative AI Tools                                 13
 Grant Writing                                        7
 Literature Review                                    4
 Programming Assistance                               7
 Research Compliance                                  1
 Research Computing                                   1
 Research Productivity                                8
 Responsible AI                                       4
 Student Learning Support                            16
 Teaching and Course Design                          11  ,
 concern_category            Academic Misconduct  Bias and Fairness  \
 main_interest_category
 AI Policy and Governance                   0.06               0.09
 Academic Writing                           0.16               0.02
 Administrative Efficiency                  0.11               0.02
 Career Development                         0.10               0.01
 Data Analysis                              0.04               0.04
 Generative AI Tools                        0.11               0.03
 Grant Writing                              0.15               0.03
 Literature Review                          0.16               0.03
 Programming Assistance                     0.12               0.01
 Research Compliance                        0.06               0.08
 Research Computing                         0.00               0.11
 Research Productivity                      0.10               0.07
 Responsible AI                             0.09               0.07
 Student Learning Support                   0.17               0.06
 Teaching and Course Design                 0.17               0.03

 concern_category            Copyright and Intellectual Property  \
 main_interest_category
 AI Policy and Governance                                   0.06
 Academic Writing                                           0.07
 Administrative Efficiency                                  0.11
 Career Development                                         0.08
 Data Analysis                                              0.09
 Generative AI Tools                                        0.05
 Grant Writing                                              0.11
 Literature Review                                          0.11
 Programming Assistance                                     0.04
 Research Compliance                                        0.00
 Research Computing                                         0.11
 Research Productivity                                      0.08
 Responsible AI                                             0.05
 Student Learning Support                                   0.03
 Teaching and Course Design                                 0.03

 concern_category            Cost and Resources  Data Privacy  \
 main_interest_category
 AI Policy and Governance                  0.15          0.15
 Academic Writing                          0.00          0.08
 Administrative Efficiency                 0.02          0.18
 Career Development                        0.01          0.11
 Data Analysis                             0.04          0.21
 Generative AI Tools                       0.06          0.16
 Grant Writing                             0.08          0.05
 Literature Review                         0.03          0.09
 Programming Assistance                    0.04          0.12
 Research Compliance                       0.11          0.19
 Research Computing                        0.04          0.21
 Research Productivity                     0.04          0.12
 Responsible AI                            0.09          0.16
 Student Learning Support                  0.01          0.14
 Teaching and Course Design                0.00          0.06

 concern_category            Hallucinations and Accuracy  Lack of Training  \
 main_interest_category
 AI Policy and Governance                           0.09              0.12
 Academic Writing                                   0.14              0.10
 Administrative Efficiency                          0.05              0.12
 Career Development                                 0.18              0.13
 Data Analysis                                      0.19              0.07
 Generative AI Tools                                0.07              0.13
 Grant Writing                                      0.08              0.09
 Literature Review                                  0.18              0.04
 Programming Assistance                             0.19              0.07
 Research Compliance                                0.00              0.11
 Research Computing                                 0.04              0.04
 Research Productivity                              0.07              0.10
 Responsible AI                                     0.09              0.14
 Student Learning Support                           0.11              0.11
 Teaching and Course Design                         0.06              0.23

 concern_category            No Major Concerns  Research Compliance  \
 main_interest_category
 AI Policy and Governance                 0.12                 0.03
 Academic Writing                         0.14                 0.03
 Administrative Efficiency                0.04                 0.07
 Career Development                       0.07                 0.01

In [ ]:
RQ2_prompt = f"""
You are helping explain workshop survey results to a non-technical audience.

Research Question 2:
What do participants want to use AI for, and what concerns are attached to those interests?

Use the summary tables below to write a clear answer.

Main AI interest counts:
{interest_counts.to_string()}

Concern category counts:
{concern_counts.to_string()}

Role by main interest:
{role_by_interest.to_string()}

Main interest by concern counts:
{interest_by_concern_counts.to_string()}

Main interest by concern percentages:
{interest_by_concern_percent.to_string()}

Write:
1. A concise answer to the research question
2. The most common AI use cases
3. The most common concerns
4. Any important relationship between interests and concerns
5. What this means for designing future AI workshops
"""

RQ2_response = client.responses.create(
    model="gpt-4.1-mini",
    input=RQ2_prompt
)

print(RQ2_response.output_text)

1. **Answer to Research Question 2:**
Participants primarily want to use AI to support student learning, assist with programming, and aid academic and grant writing. However, these interests come with significant concerns, especially around data privacy, potential academic misconduct, and the accuracy of AI outputs. There is also worry about students over-relying on AI and a general lack of training to use AI effectively and responsibly.

2. **Most Common AI Use Cases:**
- Student Learning Support
- Programming Assistance
- Generative AI Tools
- Academic Writing
- Grant Writing

3. **Most Common Concerns:**
- Data Privacy
- Academic Misconduct
- Hallucinations (incorrect AI outputs) and Accuracy
- Research Integrity
- Lack of Training
- Student Overreliance on AI

4. **Important Relationships Between Interests and Concerns:**
- Those interested in **Student Learning Support** and **Academic Writing** expressed high concerns about academic misconduct, data privacy, and overreliance on AI.
- Users focused on **Programming Assistance** and **Generative AI Tools** worry particularly about hallucinations (AI inaccuracies) and lack of training.
- Participants interested in **Research Compliance** and **AI Policy and Governance** tend to be more concerned with data privacy, security risks, and research compliance issues.
- Interests related to **Teaching and Course Design** show a strong link to concerns about student overreliance on AI and lack of training.

5. **Implications for Designing Future AI Workshops:**
- Workshops should balance teaching practical AI use cases with strong guidance on ethical and responsible use, focusing on preventing academic misconduct.
- Training on data privacy and understanding AI limitations (such as accuracy issues) must be emphasized to build trust and confidence.
- Since lack of training is a common concern, tailored tutorials for different roles (students, faculty, administrators) and uses will be beneficial.
- Addressing concerns about student overreliance by incorporating AI literacy and critical thinking about AI tools into workshops will support responsible adoption.
- Finally, including discussions on AI policy, governance, and compliance will help meet the needs of those involved in institutional decision-making and research oversight.

# RQ3

In [ ]:
# Define the allowed support pathways.
'''
These categories limit the AI output so it chooses
from this list instead of inventing new ones.
'''
support_pathways = [
    "AI Technical Consulting",
    "Teaching AI Literacy",
    "Architecture Development",
    "Infrastructure Support",
    "Research workflow consultation",
    "Teaching and Course Design Support",
    "Grant Writing Support",
    "Hackathons or workshop support",
    "Responsible AI establishment"
]

In [ ]:
# Define a JSON schema for the AI response.
# This forces the model to return structured output with the same fields every time we execute it.

schema_support_pathways = {
    "type": "object",
    "properties": {
        "Recommended_support_pathway": {
            "type": "string",
            "enum": support_pathways
        },
        "Brief_reason": {
            "type": "string"
        },
        "Explaination_phrase": {
            "type": "string"
        }
    },
    "required": ["Recommended_support_pathway", "Brief_reason", "Explanation_phrase"],
    "additionalProperties": False
}

In [ ]:
# Build the prompt for one participant row.
# The prompt gives the AI structured survey information and asks it to choose
# the best support pathway.

def prompt_function(row):
  return f"""
  You are analyzing a workshop survey feedback.

  The task here is to classify the participant into one recommend support pathway.

  Available support pathways:
  {chr(10).join("- " + p for p in support_pathways)}

  Participant information:
  Role: {row["role"]}
  Department: {row["department"]}
  Comfort with AI: {row["comfort_with_ai"]}
  Main interest: {row["main_interest_category"]} - {row["main_interest_detail"]}
  Concern: {row["concern_category"]} - {row["concern_detail"]}
  Free-text feedback: {row["free_text_feedback"]}

  Use all of the available information to make a recommendation.

  Choose the single pathway that would provide the greatest immediate benefit.
  If multiple pathways apply, select the one of themost directly supported by the participant's stated interest and concern.

  Return:
  - Recommended_support_pathway
  - Brief_reason
  - Explanation_phrase
  """

In [ ]:
# Send one participant's prompt to the AI model.
# The model returns a structured JSON response following the schema defined above.

def support_pathway_addition(row):
  prompt = prompt_function(row)

  response = client.responses.create(
      model="gpt-4.1-mini",
      input=prompt,
      text={
          "format": {
              "type": "json_schema",
              "name": "support_pathway_schema",
              "schema": schema_support_pathways,
              "strict": True
          }
      }
  )

  return json.loads(response.output_text)

###Error Handling

When using an API, some requests may fail because of `formatting issues`, `network problems`, `rate limits`, or `invalid responses`. This following function catches errors so the workflow can continue instead of stopping completely.

In [ ]:
# Classify one row and safely handle errors.
# If the API call works, we return the recommended pathway, reason, and evidence phrase.
# If it fails, we return empty values and save the error message.

def classify_row(row):
  try:
    result = support_pathway_addition(row)

    return {
        "Recommended_support_pathway": result['Recommended_support_pathway'],
      "Brief_reason": result['Brief_reason'],
      "Explanation_phrase": result['Explanation_phrase']
    }
  except Exception as e:
    return {
        "Recommended_support_pathway": None,
        "Brief_reason": None,
        "Explaination_phrase": None,
        "status": str(e)
    }

### Test the workflow on one row

Before running an AI workflow on many rows, we test it on one example. This helps confirm that the `prompt`, `schema`, and `API connection` are working.

In [ ]:
test_one_row = classify_row(data.iloc[0])
print(test_one_row)

{'Recommended_support_pathway': 'Grant Writing Support', 'Brief_reason': 'Participant is a faculty member in Public Health who is comfortable with AI and primarily interested in improving grant writing clarity and turnaround.', 'Explaination_phrase': "Given the participant's role and their expressed main interest in improving Public Health grant writing, along with concerns about AI accuracy, providing targeted support for grant writing will directly address their immediate needs and maximize benefit."}

### Complete dataset

In [ ]:
# Run the classification workflow on a selected range of rows.
# The progress bar helps us track how many rows have been processed.
# You can customize the no of rows from run_partition(data, start, end) within
# the size of the dataset

def run_partition(data, start, end):
    subset = data.iloc[start:end]
    results_set = []

    for _, row in tqdm.tqdm(
        subset.iterrows(),
        total=len(subset),
        desc=f"{start}:{end}"
    ):
        results_set.append(classify_row(row))

    return results_set

results_set = run_partition(data, 0, 100)

0:100: 100%|██████████| 100/100 [00:00<00:00, 10379.63it/s]

In [ ]:
# Convert the API results into a DataFrame and attach them to the original survey data.
# Creating a dataset with both original survey fields and AI-generated analysis.

dataset = pd.DataFrame(results_set)

analyzed_data = pd.concat([
    data.reset_index(drop=True),
    dataset.reset_index(drop=True)],
                          axis=1
                          )

In [ ]:
analyzed_data.head()

,participant_id,role,department,comfort_with_ai,main_interest_category,main_interest_detail,concern_category,concern_detail,free_text_feedback,Recommended_support_pathway,Brief_reason,Explaination_phrase
0,837645,Faculty,Public Health,Comfortable,Grant Writing,Improving clarity and turnaround on competitiv...,Hallucinations and Accuracy,Hard to verify AI output accuracy for technica...,"I already use AI fairly regularly, I'd especia...",Grant Writing Support,The participant explicitly expressed interest ...,Given the participant's focus on enhancing Pub...
1,475133,Undergraduate Student,Education,Neutral,Student Learning Support,Helping Education students use AI tutors witho...,Academic Misconduct,Students using AI to complete Education assign...,"I have mixed feelings about AI, I really want ...",Teaching AI Literacy,The participant is focused on supporting stude...,Given the participant's role as an Education u...
2,601099,Faculty,Biology,Uncomfortable,Teaching and Course Design,Designing AI-aware assignments and rubrics for...,Copyright and Intellectual Property,Unclear copyright and ownership rules for AI o...,"I've only dabbled with AI and feel uncertain, ...",Teaching and Course Design Support,The participant is a faculty member in Biology...,Given the participant's focus on teaching and ...
3,269917,Research Scientist,Computer Science,Comfortable,Data Analysis,"Cleaning, exploring, and visualizing Computer ...",Data Privacy,Unclear where AI vendors store and reuse our C...,"I already use AI fairly regularly, I'm keen to...",Responsible AI establishment,The participant is comfortable with AI and act...,Given the participant's comfort with AI and fo...
4,698457,Administrative Staff,Medicine,Neutral,Research Productivity,Cutting time spent on repetitive analysis step...,Data Privacy,Protecting confidential participant and studen...,"I have mixed feelings about AI, I'd love pract...",Research workflow consultation,The participant seeks practical ways to enhanc...,Given the participant's focus on improving res...